#!/usr/bin/env python3
"""Convert a WAV file into a C header containing a static const int16_t lookup table.

Usage:
    python scripts/wav_to_lut.py --input file.wav --output test_vector_wav.h
                                 [--rate 8000] [--duration 5] [--start 0]
                                 [--name wav_lut]
"""

import argparse
import sys
import wave
from pathlib import Path


def read_wav(path):
    with wave.open(str(path), "rb") as wf:
        nchannels = wf.getnchannels()
        sampwidth = wf.getsampwidth()
        framerate = wf.getframerate()
        nframes = wf.getnframes()
        raw = wf.readframes(nframes)

    if sampwidth == 2:
        import array

        samples = array.array("h", raw)
    elif sampwidth == 1:
        import array

        samples_8 = array.array("b", raw)
        samples = array.array("h", (s * 256 for s in samples_8))
    elif sampwidth == 4:
        import array

        samples_32 = array.array("i", raw)
        samples = array.array("h", (max(-32768, min(32767, s >> 16)) for s in samples_32))
    else:
        raise ValueError(f"unsupported sample width: {sampwidth}")

    if nchannels == 2:
        mono = array.array("h")
        for i in range(0, len(samples), 2):
            mono.append((samples[i] + samples[i + 1]) // 2)
        samples = mono
    elif nchannels > 2:
        raise ValueError(f"unsupported channel count: {nchannels}")

    return list(samples), framerate


def resample_linear(samples, src_rate, dst_rate):
    if src_rate == dst_rate:
        return samples

    ratio = dst_rate / src_rate
    out_len = int(len(samples) * ratio)
    out = []
    for i in range(out_len):
        src_pos = i / ratio
        src_idx = int(src_pos)
        frac = src_pos - src_idx
        if src_idx + 1 < len(samples):
            out.append(int(samples[src_idx] + frac * (samples[src_idx + 1] - samples[src_idx])))
        elif src_idx < len(samples):
            out.append(samples[src_idx])
        else:
            out.append(0)
    return out


def write_header(samples, name, output_path, source_path, sample_rate, duration_s):
    guard = name.upper() + "_H"
    len_macro = name.upper() + "_LEN"
    rate_macro = name.upper() + "_SAMPLE_RATE"
    header = f"""#ifndef {guard}
#define {guard}

#include <stdint.h>

/* Auto-generated by scripts/wav_to_lut.py
 * Source: {source_path}
 * Target sample rate: {sample_rate} Hz
 * Duration: {duration_s:.2f} s
 * Sample count: {len(samples)}
 */

#define {len_macro} {len(samples)}U
#define {rate_macro} {sample_rate}U

static const int16_t {name}[{len_macro}] = {{
"""
    line_parts = []
    for s in samples:
        line_parts.append(f"{s:6d}")
        if len(line_parts) == 10:
            header += "    " + ", ".join(line_parts) + ",\n"
            line_parts = []
    if line_parts:
        header += "    " + ", ".join(line_parts) + ",\n"

    header += f"""}};

#endif /* {guard} */
"""
    return header


def main():
    parser = argparse.ArgumentParser(description="Convert WAV to C header LUT")
    parser.add_argument("--input", required=True, help="Input WAV file path")
    parser.add_argument("--output", required=True, help="Output C header file path")
    parser.add_argument(
        "--rate", type=int, default=8000, help="Target sample rate in Hz (default: 8000)"
    )
    parser.add_argument(
        "--duration", type=float, default=5.0, help="Duration to extract in seconds (default: 5.0)"
    )
    parser.add_argument(
        "--start", type=float, default=0.0, help="Start offset in seconds (default: 0.0)"
    )
    parser.add_argument("--name", default="wav_lut", help="Array name (default: wav_lut)")
    args = parser.parse_args()

    input_path = Path(args.input).resolve()
    output_path = Path(args.output)
    repo_root = Path(__file__).resolve().parent.parent
    source_rel = (
        input_path.relative_to(repo_root) if input_path.is_relative_to(repo_root) else input_path
    )

    if not input_path.exists():
        print(f"Error: input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    if args.rate < 1000:
        print("Error: target rate must be >= 1000 Hz", file=sys.stderr)
        sys.exit(1)

    if args.duration <= 0:
        print("Error: duration must be positive", file=sys.stderr)
        sys.exit(1)

    print(f"Reading {input_path}...")
    samples, src_rate = read_wav(input_path)
    print(f"  Source: {len(samples)} samples, {src_rate} Hz, {len(samples) / src_rate:.2f}s")

    start_sample = int(args.start * src_rate)
    duration_samples = int(args.duration * src_rate)
    start_sample = max(0, min(start_sample, len(samples)))
    end_sample = min(start_sample + duration_samples, len(samples))
    samples = samples[start_sample:end_sample]
    print(
        f"  Extracted: {len(samples)} samples "
        f"({args.start:.2f}s - {args.start + args.duration:.2f}s)"
    )

    if args.rate != src_rate:
        print(f"  Resampling to {args.rate} Hz...")
        samples = resample_linear(samples, src_rate, args.rate)

    actual_duration = len(samples) / args.rate
    print(f"  Output: {len(samples)} samples, {args.rate} Hz, {actual_duration:.2f}s")

    header = write_header(
        samples, args.name, str(output_path), str(source_rel), args.rate, actual_duration
    )

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(header)

    size_kb = output_path.stat().st_size / 1024
    print(f"Wrote {output_path} ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
